ProFit/objects/Address_Book__c.object
<CustomObject>
    <description>Address book(Location) of the Event.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Attendee__c.object
<CustomObject>
    <description>Object for the attendees of the Event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail the Event Object.</description>
        <inlineHelpText>Event Name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship for Address Book.</description>
        <inlineHelpText>Inputted Address book for the Event.</inlineHelpText>
        <label>Address Book</label>
        <referenceTo>Address_Book__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field for Event Organizer.</description>
        <inlineHelpText>Input who is the organizer of the Event.</inlineHelpText>
        <label>Event Organizer</label>
        <referenceTo>Event_Orginizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Master Detail for Attendee Object.</description>
        <inlineHelpText>Input the attendee&apos;s Name.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Event_Orginizer__c.object
<CustomObject>
    <description>Object for the Event Organizers.</description>
    <fields>
        <fullName>Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field for the Location of the Event.</description>
        <inlineHelpText>Input the Address of the Event.</inlineHelpText>
        <label>Address Book</label>
        <referenceTo>Address_Book__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Orginizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit/classes/AttendeeEventsService.cls
public with sharing class AttendeeEventsService {
    @AuraEnabled
    public static List<Event_Attendee__c> upcomingEvents(String attendeeId) {
      List<Event_Attendee__c> eventLists = [
        SELECT
          Id,
          Name,
          Event__c,
          Event__r.Address_Book__c,
          Event__r.Address_Book__r.Name,
          Event__r.Event_Organizer__c,
          Event__r.Event_Organizer__r.Name,
          Event__r.Name,
          Event__r.Start_Date_Time__c
        FROM Event_Attendee__c
        WHERE
          Attendee__c = :attendeeId
          AND Event__r.Start_Date_Time__c >= today
          AND Event__r.Live__c = true
      ];
      return eventLists;
    }
  
    @AuraEnabled
    public static List<Event_Attendee__c> pastEvents(String attendeeId) {
      List<Event_Attendee__c> eventLists = [
        SELECT
          Id,
          Name,
          Event__c,
          Event__r.Address_Book__c,
          Event__r.Address_Book__r.Name,
          Event__r.Event_Organizer__c,
          Event__r.Event_Organizer__r.Name,
          Event__r.Name,
          Event__r.Start_Date_Time__c
        FROM Event_Attendee__c
        WHERE Attendee__c = :attendeeId AND Event__r.Start_Date_Time__c < today
       
      ];
      return eventLists;
    }
  }