ProFit/objects/Address_Book__c.object
<CustomObject>
    <description>Address book(Location) of the Event.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Exact City of the Location/Address.</description>
        <inlineHelpText>Input the exact City of the Event.</inlineHelpText>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Zip_correct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Zip verification of the Address</description>
        <inlineHelpText>This is an auto-verification checkbox.</inlineHelpText>
        <label>Is Zip correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code of the Location/Address.</description>
        <inlineHelpText>Input the postal code of the city.</inlineHelpText>
        <label>Postal Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Exact State of the Location/Address.</description>
        <inlineHelpText>Input the state of the event(If applicable)</inlineHelpText>
        <label>State</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Exact Street of the Location/Address.</description>
        <inlineHelpText>Input the exact Street of the Event.</inlineHelpText>
        <label>Street</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Verification of the Location/Address.</description>
        <inlineHelpText>Check if the Location/Address of the event is verified.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/classes/ZipVerifier_Test.cls
@isTest
public with sharing class ZipVerifier_Test {
    public static testMethod void testZip(){

        Address_Book__c loc = new Address_Book__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297'
        );
        insert loc;



        try{
            System.Test.setMock(HttpCalloutMock.class, new ZipCalloutMock());
            System.Test.startTest();

            AddressBookZipTriggerHandler.verifyZip(''+loc.Id+'');
            
            System.Test.stopTest();
        }catch(Exception ex){

        }
        Address_Book__c retrievedZipVerified = [Select Is_Zip_correct__c from Address_Book__c where Id =: loc.Id];
        System.assertEquals(true,retrievedZipVerified.Is_Zip_correct__c);

    }
    public static testMethod void testLoc(){
        Address_Book__c loc = new Address_Book__c(
            Name = '3301 South Greenfield Rd',
            Street__c = '3301 South Greenfield Rd',
            City__c = 'Gilbert',
            State__c = 'AZ',
            Postal_Code__c = '85297'
        );
        insert loc;

        try{
            System.Test.setMock(HttpCalloutMock.class, new LocationMockCallout());
            System.Test.startTest();

            AddressBookZipTriggerHandler.addressCall(''+loc.Id+'');
            
            System.Test.stopTest();
        }catch(Exception ex){

        }
        Address_Book__c retrievedLocVerified = [Select Verified__c from Address_Book__c where Id =: loc.Id];
        System.assertEquals(true,retrievedLocVerified.Verified__c);
    }

}