ProFit/objects/Address_Book__c.object
<CustomObject>
    <description>Address book(Location) of the Event.</description>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship for Address Book.</description>
        <inlineHelpText>Inputted Address book for the Event.</inlineHelpText>
        <label>Address Book</label>
        <referenceTo>Address_Book__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field for Event Organizer.</description>
        <inlineHelpText>Input who is the organizer of the Event.</inlineHelpText>
        <label>Event Organizer</label>
        <referenceTo>Event_Orginizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is occuring again.</description>
        <inlineHelpText>If the event will happen again, please put check.</inlineHelpText>
        <label>Recurring?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Orginizer__c.object
<CustomObject>
    <description>Object for the Event Organizers.</description>
    <fields>
        <fullName>Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field for the Location of the Event.</description>
        <inlineHelpText>Input the Address of the Event.</inlineHelpText>
        <label>Address Book</label>
        <referenceTo>Address_Book__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Orginizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventDetailRestService.cls
@RestResource(urlMapping = '/api/Event__c/*')
global with sharing class EventDetailRestService {
    @HTTPGet
    global static Event__c doGetEvt(){
        RestRequest req = RestContext.request;
        RestResponse resp = RestContext.response;
        String evtId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1); 
        Event__c result = [Select Id, Name, Address_Book__r.Name, Event_Organizer__r.Name, Live__c, Recurring__c, Start_Date_Time__c, End_Date_Time__c from Event__c where Id =: evtId];
        return result;
    }
}