ProFit/objects/Address_Book__c.object
<CustomObject>
    <description>Address book(Location) of the Event.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Exact City of the Location/Address.</description>
        <inlineHelpText>Input the exact City of the Event.</inlineHelpText>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Event.</description>
        <inlineHelpText>Input the County of the Event.</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burma</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Landmark__c</fullName>
        <description>Landmark of the Location/Address.</description>
        <inlineHelpText>Input what is the landmark/nearest landmark of the event&apos;s location.</inlineHelpText>
        <label>Landmark</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code of the Location/Address.</description>
        <inlineHelpText>Input the postal code of the city.</inlineHelpText>
        <label>Postal Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Exact State of the Location/Address.</description>
        <inlineHelpText>Input the state of the event(If applicable)</inlineHelpText>
        <label>State</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Exact Street of the Location/Address.</description>
        <inlineHelpText>Input the exact Street of the Event.</inlineHelpText>
        <label>Street</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Address Book</label>
    <nameField>
        <label>Address Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Attendee__c.object
<CustomObject>
    <description>Object for the attendees of the Event.</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company Name of the Attendees.</description>
        <inlineHelpText>Company Name of the Attendee.</inlineHelpText>
        <label>Company Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the Attendees.</description>
        <inlineHelpText>Primary email of the attendee.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail the Event Object.</description>
        <inlineHelpText>Event Name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact Number of the Attendees.</description>
        <inlineHelpText>Contact number of the Attendee.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Address_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship for Address Book.</description>
        <inlineHelpText>Inputted Address book for the Event.</inlineHelpText>
        <label>Address Book</label>
        <referenceTo>Address_Book__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Master Detail for Attendee Object.</description>
        <inlineHelpText>Input the attendee&apos;s Name.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Object for Event and Speaker Master Detail</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object.</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Master Detail for Speaker Object.</description>
        <inlineHelpText>Input the speaker&apos;s name.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Speaker__c.object
<CustomObject>
    <description>Speaker Object for the Event.</description>
    <fields>
        <fullName>Company__c</fullName>
        <description>Company of the Speaker.</description>
        <inlineHelpText>Input the speaker&apos;s company name.</inlineHelpText>
        <label>Company</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the Speaker.</description>
        <inlineHelpText>Valid Email Address of the Speaker.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact number of the Speaker.</description>
        <inlineHelpText>Contact number of the Speaker.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventClassController.cls
public with sharing class EventClassController {
    @AuraEnabled
    public static List<Event_Speaker__c> getSpeakers(String eventId) {
      List<Event_Speaker__c> speakerList = [
        SELECT
          Id,
          Name,
          Speaker__c,
          Speaker__r.Name,
          Speaker__r.Phone__c,
          Speaker__r.Email__c,
          Speaker__r.Company__c
        FROM Event_Speaker__c
        WHERE Event__c = :eventId
      ];
      return speakerList;
    }
  
    @AuraEnabled
    public static Event__c getLocationDetails(String eventId) {
      Event__c eventRecord = [
        SELECT
          Id,
          Name,
          Address_Book__c,
          Address_Book__r.Name,
          Address_Book__r.City__c,
          Address_Book__r.Country__c,
          Address_Book__r.Landmark__c,
          Address_Book__r.Postal_Code__c,
          Address_Book__r.State__c,
          Address_Book__r.Street__c
        FROM Event__c
        WHERE Id = :eventId
      ];
      return eventRecord;
    }
  
    @AuraEnabled
    public static List<Event_Attendee__c> getAttendees(String eventId) {
      List<Event_Attendee__c> eventAttendeeList = [
        SELECT
          Id,
          Name,
          Attendee__c,
          Attendee__r.Name,
          Attendee__r.Email__c,
          Attendee__r.Company_Name__c
        FROM Event_Attendee__c
        WHERE Event__c = :eventId
      ];
      return eventAttendeeList;
    }
}