ProFit/objects/Attendee__c.object
<CustomObject>
    <description>Object for the attendees of the Event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail the Event Object.</description>
        <inlineHelpText>Event Name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Field on how many seats is accomodated by the Event</description>
        <inlineHelpText>Maximum capacity of the event.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is occuring again.</description>
        <inlineHelpText>If the event will happen again, please put check.</inlineHelpText>
        <label>Recurring?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Master Detail for Attendee Object.</description>
        <inlineHelpText>Input the attendee&apos;s Name.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Object for Event and Speaker Master Detail</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object.</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Master Detail for Speaker Object.</description>
        <inlineHelpText>Input the speaker&apos;s name.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Speaker__c.object
<CustomObject>
    <description>Speaker Object for the Event.</description>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFit/classes/EventClassController_Test.cls
@isTest
public with sharing class EventClassController_Test {
    static Id createTestEvent(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Recurring__c = true;
        evt.Max_Seats__c = 10;
        evt.Start_Date_Time__c = datetime.newInstance(2021, 06, 27, 12, 0, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 06, 28, 12, 0, 0);
        insert evt;
        return evt.Id;
    }
    static Id createTestSpeaker(){
        Speaker__c spk = new Speaker__c();
        spk.Name = 'Test Speaker';
        insert spk;
        return spk.Id;
    }
    static Id createTestAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee';
        att.Event__c = createTestEvent();
        insert att;
        return att.Id;
    }
    @IsTest
    static void testSpeaker(){
        
        System.Test.startTest();
        String recId;
        Event_Speaker__c eS = new Event_Speaker__c();
        eS.Event__c = createTestEvent();
        eS.Speaker__c = createTestSpeaker();
        eS.Name = 'Test Name';
        Event_Speaker__c name;
        String str = '';
        insert eS;
        List<Event_Speaker__c> retrievedSpeaker = EventClassController.getSpeakers(eS.Event__c);
        name = retrievedSpeaker.get(0);
        System.Test.stopTest();
        System.assertEquals('Test Name',name.Name);
    }
    @IsTest
    static void testLocation(){
        System.Test.startTest();
        String recId = createTestEvent();
        Event__c evts = EventClassController.getLocationDetails(recId);
        System.Test.stopTest();
        System.assertEquals('Test Event',evts.Name);
    }
    @IsTest
    static void testAttendee(){
        System.Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        eA.Attendee__c = createTestAttendee();
        eA.Event__c = createTestEvent();
        eA.Name = 'Test Event';
        insert eA;
        Event_Attendee__c name;
        List<Event_Attendee__c> retrievedAttendee = EventClassController.getAttendees(eA.Event__c);
        name = retrievedAttendee.get(0);
        System.Test.stopTest();
        System.assertEquals('Test Event', name.Name);
    }
}