ProFit/objects/Attendee__c.object
<CustomObject>
    <description>Object for the attendees of the Event.</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail the Event Object.</description>
        <inlineHelpText>Event Name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Field on how many seats is accomodated by the Event</description>
        <inlineHelpText>Maximum capacity of the event.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFit/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Master Detail for Attendee Object.</description>
        <inlineHelpText>Input the attendee&apos;s Name.</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Attendee</relationshipLabel>
        <relationshipName>Event_Attendee</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AttendeeEventsController_Test.cls
@isTest
public with sharing class AttendeeEventsController_Test {
    static Id createTestNewEvent(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Start_Date_Time__c = datetime.newInstance(2021, 7, 21, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 7, 22, 19, 30, 0);
        evt.Live__c = true;
        evt.Max_Seats__c = 10;
        insert evt;
        return evt.Id;
    }
    static Id createTestOldEvent(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Start_Date_Time__c = datetime.newInstance(2021, 3, 21, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 3, 22, 19, 30, 0);
        evt.Live__c = false;
        evt.Max_Seats__c = 10;
        insert evt;
        return evt.Id;
    }
    static Id createTestNewAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee';
        att.Event__c = createTestNewEvent();
        insert att;
        return att.Id;
    }
    static Id createTestOldAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee';
        att.Event__c = createTestOldEvent();
        insert att;
        return att.Id;
    }
    @isTest
    static void testUpcomingEvents(){
        System.Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        Attendee__c att = new Attendee__c();
        eA.Event__c = createTestNewEvent();
        eA.Attendee__c = createTestNewAttendee();
        eA.Name = 'Test EA';
        insert eA;
        Event_Attendee__c name;
        List<Event_Attendee__c> retrievedAttendee = AttendeeEventsService.upcomingEvents(eA.Attendee__c);
        name = retrievedAttendee.get(0);
        
        System.Test.stopTest();
        System.assertEquals('Test EA', name.Name);
    }
    @isTest
    static void testPastEvents(){
        System.Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        eA.Event__c = createTestOldEvent();
        eA.Attendee__c = createTestOldAttendee();
        eA.Name = 'Test EA';
        insert eA;
        Event_Attendee__c name;
        List<Event_Attendee__c> retrievedAttendee = AttendeeEventsService.pastEvents(eA.Attendee__c);
        name = retrievedAttendee.get(0);
        
        System.Test.stopTest();
        System.assertEquals('Test EA', name.Name);
    }
}