ProFit/objects/Error_Log__c.object
<CustomObject>
    <description>Stores all of the error in the Application.</description>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <description>Date and time when the error occured.</description>
        <inlineHelpText>Input the date and time when the error occured.</inlineHelpText>
        <label>Log Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log_Details__c</fullName>
        <description>Detail of the error.</description>
        <inlineHelpText>Explain the details of the error.</inlineHelpText>
        <label>Log Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>The name of either Apex Class or Apex Trigger error.</description>
        <inlineHelpText>Name of the Apex Class or Trigger that has error.</inlineHelpText>
        <label>Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ErrorLogGenerator_Test.cls
@isTest
public with sharing class ErrorLogGenerator_Test {
    @IsTest
    static void testError(){
        
        System.Test.startTest();
        Datetime logdatetime = datetime.newInstance(2021, 6, 21, 19, 30, 0);
        String logdetails = 'Error Test';
        String pname = 'Test Error Name';
        ErrorLogProFit.createErrorLog(logdatetime, logdetails, pname);

        System.Test.stopTest();
        Error_Log__c eLog = [Select Id, Log_Date_Time__c,Log_Details__c,Process_Name__c from Error_Log__c];
        System.assertEquals('Test Error Name', eLog.Process_Name__c);
    }
}