objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Object for Event and Speaker Master Detail</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object.</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Master Detail for Speaker Object.</description>
        <inlineHelpText>Input the speaker&apos;s name.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Speaker__c.object
<CustomObject>
    <description>Speaker Object for the Event.</description>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SpeakerDuplicate.cls
public with sharing class SpeakerDuplicate {
    public static void checkDuplicate(List<Event_Speaker__c> newSpeakerList) {
       try {
           for(Event_Speaker__c spk : newSpeakerList){
   
               Event__c evtDate = [Select Start_Date_Time__c,End_Date_Time__c from Event__c where Id = :spk.Event__c];
               List<Event_Speaker__c> spkCount = [Select Id,Event__c,Speaker__c from Event_Speaker__c where (Speaker__c = :spk.Speaker__c 
                                                                                 AND Event__c != :spk.Event__c)
                                                                                 AND((Event__r.Start_Date_Time__c <  :evtDate.End_Date_Time__c
                                                                                   AND Event__r.End_Date_Time__c     >  :evtDate.End_Date_Time__c) 
                                                                                   OR(Event__r.Start_Date_Time__c      <  :evtDate.Start_Date_Time__c
                                                                                    AND Event__r.End_Date_Time__c     >  :evtDate.Start_Date_Time__c)
                                                                                    OR(Event__r.Start_Date_Time__c >= :evtDate.Start_Date_Time__c
                                                                                    AND Event__r.End_Date_Time__c <= :evtDate.End_Date_Time__c))  ];                                                       
               
                if(spkCount.size()>0){
                    spk.Speaker__c.addError('The Speaker has an existing event already.');
                }
               
           }
       } catch (Exception ex) {
           System.debug('Exception -- ' + ex.getMessage());
       }
    }
}