objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Object for Event and Speaker Master Detail</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Master Detail for Event Object.</description>
        <inlineHelpText>Input the Event name.</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Master Detail for Speaker Object.</description>
        <inlineHelpText>Input the speaker&apos;s name.</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event-Speaker</relationshipLabel>
        <relationshipName>Event_Speaker</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFit/objects/Speaker__c.object
<CustomObject>
    <description>Speaker Object for the Event.</description>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speaker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SetEventSpeaker_Test.cls
@isTest
private class SetEventSpeaker_Test {
    
    Static Id createTestRecordID(){
        Event__c evt = new Event__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Start_Date_Time__c = datetime.newInstance(2021, 6, 21, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 6, 22, 20, 30, 0);
        insert evt;
        return evt.Id;
    }

        @IsTest
      Static void checkEventEspeaker(){
        System.Test.startTest();

        try{
        Event_Speaker__c eS = new Event_Speaker__c();
        //Field Names
        //Create a new data to object
        eS.Name = 'Test Event-Speaker';
        eS.Event__c = createTestRecordID();
        eS.Speaker__c = 'a080l00000BCp3bAAD';
        
        insert eS;
        

        Event_Speaker__c retrievedES = [Select Name from Event_Speaker__c where Name =: eS.Name];

        System.assertEquals('Test Event-Speaker',retrievedES.Name);
        }
        catch (Exception ex){
          System.Test.stopTest();
        }
      }

    
}