objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Input when will the event exactly ends.</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is Live or not.</description>
        <inlineHelpText>Is the event on-going or valid?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Field on how many seats is accomodated by the Event</description>
        <inlineHelpText>Maximum capacity of the event.</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the Event is occuring again.</description>
        <inlineHelpText>If the event will happen again, please put check.</inlineHelpText>
        <label>Recurring?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the Event.</description>
        <inlineHelpText>Starting date and time of the event.</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist for event status.</description>
        <inlineHelpText>Status of the event.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchDeleteEventTest.cls
@IsTest
private class BatchDeleteEventTest {
    @IsTest
    static void validateEventStatus(){
        Event__c evt = new Event__c();
        evt.Name = 'Event Sample';
        evt.Live__c = false;
        evt.Recurring__c = true;
        evt.Max_Seats__c = 10;
        evt.Start_Date_Time__c = datetime.newInstance(2020, 12, 21, 12, 0, 0);
        evt.End_Date_Time__c = datetime.newInstance(2020, 12, 22, 12, 0, 0);
        evt.Status__c = 'Published';
        insert evt;

        System.Test.startTest();
            DeleteEventBatch eventdelete = new DeleteEventBatch();
            database.executeBatch(eventdelete);
        System.Test.stopTest();

        Event__c createdEvent = [Select Status__c from Event__c where Id =: evt.Id];
        System.assertEquals('Deleted', createdEvent.Status__c);         

    }
}